// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEmployee(arg1) {
  return window['go']['app']['App']['AddEmployee'](arg1);
}

export function ListEmployees() {
  return window['go']['app']['App']['ListEmployees']();
}

export function RemoveEmployee(arg1) {
  return window['go']['app']['App']['RemoveEmployee'](arg1);
}

export function TeamPulseOverview() {
  return window['go']['app']['App']['TeamPulseOverview']();
}
