// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {employees} from '../models';
import {overview} from '../models';

export function AddEmployee(arg1:employees.Input):Promise<employees.Employee>;

export function ListEmployees():Promise<Array<employees.Employee>>;

export function RemoveEmployee(arg1:number):Promise<void>;

export function TeamPulseOverview():Promise<overview.Overview>;
